### ISSUE TITLE
plugin.video.vavooto-5.9.3.6

### ISSUE THREAD

**Issue by Simpsonnn** [michaz1988/michaz1988.github.io#2]
Hallo an den/die Entwickler dieses tollen Addons für Kodi,

leider kann ich unter Kodi 20.2 das Addon nicht installieren und im LOG steht folgendes:

`2023-08-05 11:17:24.380 T:9996    error <general>: CAddonInstallJob[plugin.video.vavooto]: Die Abhängigkeit auf script.module.vavoo in Version 0.0.0 konnte nicht aufgelöst werden.`

Für Testzwecke habe ich in Addons.xml folgende Zeile auskommentiert:

`<import addon="script.module.vavoo"/>`

Dann lässt sich das Addon zwar installieren, aber beim Start des Addons erhält man neue Fehler:

`2023-08-05 11:41:22.320 T:4260     info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: plugin.video.vavooto v5.9.3.6 installed
2023-08-05 11:41:29.030 T:13152    info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2023-08-05 11:41:32.367 T:1320    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'vavoosigner'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\XXXXXXX\AppData\Roaming\Kodi\addons\plugin.video.vavooto\main.py", line 7, in <module>
                                                       from resources.lib import utils, vjlive, vjackson
                                                     File "C:\Users\XXXXXXX\AppData\Roaming\Kodi\addons\plugin.video.vavooto\resources\lib\vjlive.py", line 2, in <module>
                                                       import sys, re, requests, time, xbmcgui, xbmc, json, vavoosigner
                                                   ModuleNotFoundError: No module named 'vavoosigner'
                                                   -->End of Python script error report<--`

Ist das Addon unter Kodi 20 nicht lauffähig oder mache ich etwas Grundlegendes falsch?

**Comment by michaz1988** [comment]
du brauchst meine repo dann wird das modul mitinstalliert

**Comment by Simpsonnn** [comment]
Wie bekommt man Dein Repo? Was sind die Bedingungen dafür?

**Comment by michaz1988** [comment]
https://michaz1988.github.io/

**Comment by Simpsonnn** [comment]
vielen dank - saubere arbeit. jetzt funktioniert vavoo auch ohne probleme.

**Comment by kasi45** [comment]
moin,
man(n) kann immer wieder etwas lernen wenn ich mir den Stil von deinem Code anschaue. DANKE!

Eine Kleinigkeit sollte aber noch angepasst werden - im File mit 'kasi' gekennzeichnet.
[vjackson.py.txt](https://github.com/michaz1988/michaz1988.github.io/files/12445060/vjackson.py.txt)

Ohne die Anpassung wird die "Menu Route" verlassen wenn ein Stream bis zum Ende gelaufen ist.

**Comment by kasi45** [comment]
und nur für de "Schönheit"
```
def createListItem(params):
	data = utils.get_meta(params)
	if not data: return
	infos = data["infos"]
	if params.get("e"):o = ListItem("S%sxE%s %s" %(params["s"], params["e"], infos["title"]) , infos["title"])
	else: o = ListItem('%s (%s)' %(infos["title"], infos["year"])) if 'year' in infos and infos["year"] else ListItem(infos["title"])	# edit by kasi
	o.setInfo("Video", infos)
	o.setProperties(data["properties"])
	art = data["art"]
	if art.get("poster"): art["icon"] = art["poster"]
	if art.get("thumb"): art["poster"] = art["thumb"]
	o.setArt(art)
	o.setCast(data["cast"])
	o.setUniqueIDs(data["ids"], "tmdb")
	return o
```

**Comment by kasi45** [comment]
@michaz1988
Änderungen für Kodi 20+ ( listitem - setinfo - InfoTagVideo)
https://github.com/xs-home/plugin.video.vavooto
