### ISSUE TITLE
Could not Connect

### ISSUE THREAD

**Issue by Dragonstylez** [michaz1988/michaz1988.github.io#20]
Hello @michaz1988 ,

For a few days I have had the problem that the repo cannot be reached after installing the zip file. With my old stick I can use it without any problems, but a fresh installation doesn't work. I tested it not only on myself but also on two friends, which is why I think it may have something to do with an update. It always says there when I want to access the repo to install something
“could not connect” would be great if you could take a look.

![Unbenannt](https://github.com/user-attachments/assets/889b7785-58e3-4742-9db5-2fb0841264c6)

**Comment by Dragonstylez** [comment]
![e0c51a26-d2d3-48ec-a157-00d07641df1b](https://github.com/user-attachments/assets/4fac48d5-2658-4ead-8664-51e9b494e493)

**Comment by Lulu5353** [comment]
Same problem...

**Comment by last0tt0man** [comment]
same to me

**Comment by Dragonstylez** [comment]
Fixed with the new ZIP 4.5 Thx @michaz1988

**Comment by GoroGoraK** [comment]
Hi !
Is the problem relevant again? I've been having the same problem for several days

**Comment by Dragonstylez** [comment]
> Hi @Dragonstylez Is the problem relevant again? I've been having the same problem for several days

I dont know. i did no fresh install in a while but as i heard from a friend when i asked he said it still worked a few days ago.

**Comment by pocki87** [comment]
Hab es heute probiert und ja beim neu aufgesetzen.. ist die repo wieder nicht erreichbar.. wer schon drauf hat der hat auch keine Probleme

**Comment by carpediem2309** [comment]
No it's been a while that's it's been down at least s month I know for sure
cozZ my b day was 23.09. and I bought my self  a new box and I couldn't
install the repo 😔

**Comment by GoroGoraK** [comment]
@Dragonstylez , you can reoppen this issue, or we must open an another new issue ?

**Comment by GoroGoraK** [comment]
It works now, i've try with the 4.7 zip version.
Thx @michaz1988

**Comment by pocki87** [comment]
@michaz1988 Vielen lieben Dank für die  Mühe... Ich weiß es sehr zu schätzen die Arbeit die da hinter steckt...
