### ISSUE TITLE
Xstream and xstream scrapper bug

### ISSUE THREAD

**Issue by stickdrift29** [michaz1988/michaz1988.github.io#22]
Xstream addon can’t start when the xstream scrapper is installed

**Comment by Sloth1973** [comment]
Good morning,

als erstes: Danke fürs weiterentwickeln.

Und nun als zweites - ich denke ich habe den Fehler gefunden:
repo/addons.xml Zeile 295:  name="xStream Scraper" version="0.2.1"

Doch in den Ordnernamen und den Dateinamen hat sich eine >1< eingeschlichen.
repo/script.module.xstream>1</script.module.xstream**>1<-0.2.2.zip

Hoffe das hilft Dir und somit auch mir weiter ;-)

**Comment by michaz1988** [comment]
morgen,

Ich musste die addon id umbenennen damit XStream wieder normal funktioniert.

Da haben die Entwickler von XStream wohl was eingebaut.


XStream-Scraper einmal deinstallieren und neu installieren dann läuft wieder alles


mfg

**Comment by michaz1988** [comment]
Achja die die Player müssen auch aktualisiert werden 

Xstream-Scraper->Einstellungen  und auf TMDB-HELPER einrichten klicken

**Comment by stickdrift29** [comment]
Alles erledigt, xstream lässt sich auch wie gewohnt wieder starten, allerdings funktioniert bei mir der scrapper nicht richtig, wählt dieser vavoo aus kein Problem, laufen die Seiten über xStream werden keine Seiten gefunden. Wähle ich als Beispiel Serienstream aus als Abspielen dann funktioniert es ( also unahbhängug von dem scrapper). Oder habe ich etwas falsch eingestellt 🙈?

**Comment by stickdrift29** [comment]
Alles läuft wieder :) danke für den fix
