### ISSUE TITLE
Players.zip lässt sich nicht installieren

### ISSUE THREAD

**Issue by BenMaster1978** [michaz1988/michaz1988.github.io#26]
Hallo Michaz1988,

bei dem Obtober-Release der Players.zip scheint etwas nicht zu stimmen. Der Xstream Scraper zeigt einen Fehler und es werden keine Dateien (Abspieler) entpackt. Die Datei aus August scheint zu funktionieren.  Kannst du dir das bitte anschauen?

Gruß,

Ben

**Comment by carpediem2309** [comment]
I am Michael
Pozz

**Comment by StefanRu1** [comment]
Hi,

das players.zip von vor 2 Tagen, commit [4f057e3] hat 0 Byte ("0 lines (0 loc) · 0 Bytes").

Gruß,
Stefan
