### ISSUE TITLE
Hi gibt es eine Lösung für die zappen.tv repo 

### ISSUE THREAD

**Issue by Fatih1988x** [michaz1988/michaz1988.github.io#4]
Hi michaz gibt es eine Lösung für die zappen.tv repo bei mir ist die komplett leer ich benutze kein live TV nur die Mediathek und da geht garnix mehr würde nicht echt sehr freuen wenn es eine Lösung geben würde.

**Comment by michaz1988** [comment]
jein das joyn addon ersetzt zappn
