### ISSUE TITLE
Xship spielt keine Vavoo streams

### ISSUE THREAD

**Issue by urs45** [michaz1988/michaz1988.github.io#4]
Die Vavoo streams werden gefunden aber werden nicht abgespielt

**Comment by Barclay6969** [comment]
Ich habe es hinbekommen das xShip die Vavoo Streams abspielt. Ebenfalls Kkiste läuft wieder. Neben den anderen Filmpalast, Kinoger und Kinox. Serienstream habe ich leider nicht hingekriegt. Aber Vavoo kompensiert das schon ziemmlich gut.
@michaz1988 hast Du selber eine Lösung für dieses Issue oder möchtest Du meine plugin.video.xship.zip?

**Comment by urs45** [comment]
ich hätte auf jeden Fall Interesse, genau Vavoo ist bei Serien der ideal Backup wenn Serienstream nicht funktioniert

**Comment by urs45** [comment]
Danke, hat funktioniert 
hier noch eine angepasste Vavoo.json für TmdbHelper. Die Originale funktioniert bei mir nur für Filme.
[vavoo.json](https://github.com/michaz1988/michaz1988.github.io/files/14361068/vavoo.json)

**Comment by Barclay6969** [comment]
Hey super, die wollte ich auch noch anpassen. Bist Mega. Vielen Dank & viel Spass.

Serienstream über xShip läuft bei Dir? Ich habs leider nicht hingekriegt, dass die Streams starten

**Comment by urs45** [comment]
Nein Serienstream läuft bei mir auch nicht über X-ship. Findet gar keine streams.

**Comment by Cihanx30** [comment]
Wie kannst du Serienstream schauen ? 

Bei mir funktioniert nichts

**Comment by Barclay6969** [comment]
Gehe über Abspielen mit Vavoo.to greift auch auf Serienstream zu.
